apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t10a
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-t10a@sha256:aa536ab5c19944c69e7c61deba44d1ed243680c1b32cc830c74499a8d0307fcf
        name: my-nodejs
        resources: {}
status: {}
